"""schema iniziale

Revision ID: 56dda7f5137f
Revises:
Create Date: 2026-07-20 13:46:21.577484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56dda7f5137f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('appuntamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('servizio', sa.String(length=100), nullable=False),
    sa.Column('data', sa.String(length=20), nullable=False),
    sa.Column('ora', sa.String(length=10), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('stato', sa.String(length=20), nullable=True),
    sa.Column('creato_il', sa.DateTime(), nullable=True),
    sa.Column('google_event_id', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('call_sonno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('eta_bambino_mesi', sa.Integer(), nullable=False),
    sa.Column('difficolta_principale', sa.String(length=120), nullable=False),
    sa.Column('difficolta_altro', sa.String(length=300), nullable=True),
    sa.Column('consenso_privacy', sa.Boolean(), nullable=False),
    sa.Column('data', sa.String(length=20), nullable=False),
    sa.Column('ora', sa.String(length=10), nullable=False),
    sa.Column('stato', sa.String(length=20), nullable=False),
    sa.Column('google_event_id', sa.String(length=255), nullable=True),
    sa.Column('formula_scelta', sa.String(length=30), nullable=True),
    sa.Column('token_questionario', sa.String(length=96), nullable=True),
    sa.Column('questionario_inviato_il', sa.DateTime(), nullable=True),
    sa.Column('creato_il', sa.DateTime(), nullable=False),
    sa.Column('aggiornato_il', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('call_sonno', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_call_sonno_data'), ['data'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_sonno_stato'), ['stato'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_sonno_token_questionario'), ['token_questionario'], unique=True)

    op.create_table('corso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titolo', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=True),
    sa.Column('descrizione', sa.Text(), nullable=True),
    sa.Column('data', sa.String(length=20), nullable=False),
    sa.Column('ora', sa.String(length=10), nullable=True),
    sa.Column('luogo', sa.String(length=200), nullable=True),
    sa.Column('durata_ore', sa.Float(), nullable=False),
    sa.Column('capienza_massima', sa.Integer(), nullable=True),
    sa.Column('stato', sa.String(length=20), nullable=False),
    sa.Column('creato_il', sa.DateTime(), nullable=True),
    sa.Column('google_event_id', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('percorso_accompagnamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titolo', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('descrizione', sa.Text(), nullable=True),
    sa.Column('capienza_coppie', sa.Integer(), nullable=True),
    sa.Column('luogo', sa.String(length=200), nullable=True),
    sa.Column('contatti', sa.String(length=200), nullable=True),
    sa.Column('stato', sa.String(length=20), nullable=False),
    sa.Column('creato_il', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('persona_corso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('codice_fiscale', sa.String(length=32), nullable=True),
    sa.Column('nome_bambino', sa.String(length=100), nullable=True),
    sa.Column('eta_bambino', sa.String(length=40), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('creato_il', sa.DateTime(), nullable=True),
    sa.Column('aggiornato_il', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registro_evento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=40), nullable=False),
    sa.Column('esito', sa.String(length=20), nullable=False),
    sa.Column('messaggio', sa.Text(), nullable=False),
    sa.Column('entita_tipo', sa.String(length=80), nullable=True),
    sa.Column('entita_id', sa.Integer(), nullable=True),
    sa.Column('dettagli', sa.Text(), nullable=True),
    sa.Column('creato_il', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('registro_evento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registro_evento_categoria'), ['categoria'], unique=False)
        batch_op.create_index(batch_op.f('ix_registro_evento_creato_il'), ['creato_il'], unique=False)
        batch_op.create_index(batch_op.f('ix_registro_evento_entita_id'), ['entita_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_registro_evento_entita_tipo'), ['entita_tipo'], unique=False)
        batch_op.create_index(batch_op.f('ix_registro_evento_esito'), ['esito'], unique=False)

    op.create_table('incontro_accompagnamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('percorso_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('data', sa.String(length=20), nullable=False),
    sa.Column('ora', sa.String(length=10), nullable=True),
    sa.Column('professionista', sa.String(length=100), nullable=False),
    sa.Column('tema', sa.String(length=200), nullable=False),
    sa.Column('luogo', sa.String(length=200), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('creato_il', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['percorso_id'], ['percorso_accompagnamento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iscrizione_corso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corso_id', sa.Integer(), nullable=True),
    sa.Column('persona_id', sa.Integer(), nullable=True),
    sa.Column('percorso_accompagnamento_id', sa.Integer(), nullable=True),
    sa.Column('corso_tipo', sa.String(length=80), nullable=False),
    sa.Column('corso_titolo', sa.String(length=200), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('codice_fiscale', sa.String(length=32), nullable=False),
    sa.Column('data_corso', sa.String(length=20), nullable=True),
    sa.Column('partecipazione', sa.String(length=100), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('dati_extra', sa.Text(), nullable=True),
    sa.Column('tipo_richiesta', sa.String(length=40), nullable=False),
    sa.Column('posti', sa.Integer(), nullable=False),
    sa.Column('consenso_privacy', sa.Boolean(), nullable=False),
    sa.Column('consenso_immagini', sa.Boolean(), nullable=False),
    sa.Column('stato', sa.String(length=20), nullable=False),
    sa.Column('creato_il', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['corso_id'], ['corso.id'], ),
    sa.ForeignKeyConstraint(['percorso_accompagnamento_id'], ['percorso_accompagnamento.id'], ),
    sa.ForeignKeyConstraint(['persona_id'], ['persona_corso.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questionario_sonno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_sonno_id', sa.Integer(), nullable=False),
    sa.Column('risposte', sa.Text(), nullable=False),
    sa.Column('consenso_dati_sanitari', sa.Boolean(), nullable=False),
    sa.Column('consenso_marketing', sa.Boolean(), nullable=False),
    sa.Column('compilato_il', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['call_sonno_id'], ['call_sonno.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_sonno_id')
    )
    op.create_table('presenza_accompagnamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iscrizione_id', sa.Integer(), nullable=False),
    sa.Column('incontro_id', sa.Integer(), nullable=False),
    sa.Column('presente', sa.Boolean(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('aggiornata_il', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['incontro_id'], ['incontro_accompagnamento.id'], ),
    sa.ForeignKeyConstraint(['iscrizione_id'], ['iscrizione_corso.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('presenza_accompagnamento')
    op.drop_table('questionario_sonno')
    op.drop_table('iscrizione_corso')
    op.drop_table('incontro_accompagnamento')
    with op.batch_alter_table('registro_evento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registro_evento_esito'))
        batch_op.drop_index(batch_op.f('ix_registro_evento_entita_tipo'))
        batch_op.drop_index(batch_op.f('ix_registro_evento_entita_id'))
        batch_op.drop_index(batch_op.f('ix_registro_evento_creato_il'))
        batch_op.drop_index(batch_op.f('ix_registro_evento_categoria'))

    op.drop_table('registro_evento')
    op.drop_table('persona_corso')
    op.drop_table('percorso_accompagnamento')
    op.drop_table('corso')
    with op.batch_alter_table('call_sonno', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_call_sonno_token_questionario'))
        batch_op.drop_index(batch_op.f('ix_call_sonno_stato'))
        batch_op.drop_index(batch_op.f('ix_call_sonno_data'))

    op.drop_table('call_sonno')
    op.drop_table('appuntamento')
    op.drop_table('admin')
    # ### end Alembic commands ###
